version: '3.2'

services:
  web-services-api:
    build:
      context: .
      dockerfile: build/Dockerfile
    command: python manage.py runserver 0.0.0.0:8080
    container_name: smartgender-api
    environment:
      DJANGO_SETTINGS_MODULE: django_test.settings
      IPYTHONDIR: /home/web/.ipython
    image: web_services
    ports:
     - 8000:8080
    restart: always
    stdin_open: true
    tty: true
    volumes:
     - ./:/app/src
     - ~/.ipython/:/home/web/.ipython/

volumes:
  data:
